

jasypt:
  encryptor:
    password: ${ORDERS_JASYPT_PASSWORD}

server:
  port: 8082

auth:
  permitAll: /kitchen-orders/v1/profile,/kitchen-orders/v1,/orders/v1/foods,/orders/v1/foods/action,orders/v1/foods/stripe-payments/payment-intent,/kitchen-orders/v1/sales-profile,/invoices,/invoices/*
spring:
  data:
    mongodb:
      uri: ${ORDERS_DB_URI}
      database: ${ORDERS_DB_NAME}
  mail:
    default-encoding: UTF-8
    host: ${SMTP_SERVER:smtp.gmail.com}
    username: ${ORDERS_EMAIL}
    password: ${ORDERS_EMAIL_PASSWORD} 
    port: 587
    debug: true
    properties:
      mail:
        store:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# Enable or disable Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

application:
  send-email-confirmation: false

smtp:
  server: ${SMTP_SERVER:smtp.gmail.com}
  username: ${ORDERS_EMAIL}
  password: ${ORDERS_EMAIL_PASSWORD}
  debug: true

stripe:
  private:
    key: ${ORDERS_STRIPE_SECRET_KEY}
  success:
    url: ${ORDERS_STRIPE_SUCCESS_URL}
  cancel:
    url: ${ORDERS_STRIPE_CANCEL_URL}
  currency: ${ORDERS_STRIPE_CURRENCY:gbp}
